// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { createRequire } from "node:module";
import { defineConfig } from "prisma/config";

const require = createRequire(import.meta.url);

try {
  require("dotenv/config");
} catch {
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
});
